baseURL = 'https://example.org/'
locale = 'en-us'
title = 'HD 189 b'
theme = 'minimali'
buildFuture = true
disableKinds = ["sitemap"]



DisableSitemap = true


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
  	name ='Blogs'
	pageRef = "/blogs"
	weight = 20

  [[menus.main]]
  	name = 'Book Review'
	pageRef = '/books'
	weight = 30

  [[menus.main]]
  	name = 'Contact'
	pageRef = '/contact'
	weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'


[markup.goldmark.renderer]
unsafe = true

